-- VHDL Entity Wasmachine.Master.interface
--
-- Created:
--          by - Perij.UNKNOWN (LAPTOP-Q0P13GKH)
--          at - 15:33:50 11/03/2025
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.1 Built on 21 Jan 2022 at 13:00:30
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY Master IS
   PORT( 
      aan_uit       : IN     std_logic;
      clk           : IN     std_logic;
      deur_dicht    : IN     std_logic;
      kuip_leeg     : IN     std_logic;
      start         : IN     std_logic;
      w_hoog        : IN     std_logic;
      w_laag        : IN     std_logic;
      wassen_ready  : IN     std_logic;
      wassen_status : IN     std_logic_vector (2 DOWNTO 0);
      deur_grendel  : OUT    std_logic;
      go_wassen     : OUT    std_logic;
      led_start     : OUT    std_logic;
      led_status    : OUT    std_logic_vector (2 DOWNTO 0)
   );

-- Declarations

END Master ;

--
-- VHDL Architecture Wasmachine.Master.Master
--
-- Created:
--          by - Perij.UNKNOWN (LAPTOP-Q0P13GKH)
--          at - 11:54:55 21/03/2025
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.1 Built on 21 Jan 2022 at 13:00:30
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
 
ARCHITECTURE Master OF Master IS

   TYPE STATE_TYPE IS (
      idle,
      proces,
      wait_s,
      started,
      L_status,
      prg_done,
      s_spoelstop,
      s0,
      s1
   );
 
   -- Declare current and next state signals
   SIGNAL current_state : STATE_TYPE;
   SIGNAL next_state : STATE_TYPE;

BEGIN

   -----------------------------------------------------------------
   clocked_proc : PROCESS ( 
      clk,
      aan_uit
   )
   -----------------------------------------------------------------
   BEGIN
      IF (aan_uit = '0') THEN
         current_state <= idle;
      ELSIF (clk'EVENT AND clk = '1') THEN
         current_state <= next_state;
      END IF;
   END PROCESS clocked_proc;
 
   -----------------------------------------------------------------
   nextstate_proc : PROCESS ( 
      current_state,
      deur_dicht,
      start,
      wassen_ready,
      wassen_status
   )
   -----------------------------------------------------------------
   BEGIN
      CASE current_state IS
         WHEN idle => 
            IF (start = '0') THEN 
               next_state <= idle;
            ELSIF (start = '1' AND
                   deur_dicht = '1') THEN 
               next_state <= proces;
            ELSE
               next_state <= idle;
            END IF;
         WHEN proces => 
            IF (wassen_ready = '1') THEN 
               next_state <= wait_s;
            ELSIF (start = '0') THEN 
               next_state <= idle;
            ELSIF (start = '1') THEN 
               next_state <= proces;
            ELSE
               next_state <= proces;
            END IF;
         WHEN wait_s => 
            IF (wassen_ready = '0') THEN 
               next_state <= started;
            ELSIF (wassen_ready = '1') THEN 
               next_state <= wait_s;
            ELSE
               next_state <= wait_s;
            END IF;
         WHEN started => 
            IF (wassen_ready = '0') THEN 
               next_state <= L_status;
            ELSE
               next_state <= started;
            END IF;
         WHEN L_status => 
            IF (wassen_status = "101") THEN 
               next_state <= s_spoelstop;
            ELSIF (wassen_ready = '1') THEN 
               next_state <= prg_done;
            ELSIF (wassen_ready = '0') THEN 
               next_state <= L_status;
            ELSIF (wassen_status = "011" OR wassen_status = "110") THEN 
               next_state <= s0;
            ELSE
               next_state <= L_status;
            END IF;
         WHEN prg_done => 
            next_state <= idle;
         WHEN s_spoelstop => 
            IF (start = '0') THEN 
               next_state <= s_spoelstop;
            ELSIF (start = '1') THEN 
               next_state <= s1;
            ELSE
               next_state <= s_spoelstop;
            END IF;
         WHEN s0 => 
            next_state <= L_status;
         WHEN s1 => 
            IF (wassen_status /= "101") THEN 
               next_state <= L_status;
            ELSE
               next_state <= s1;
            END IF;
         WHEN OTHERS =>
            next_state <= idle;
      END CASE;
   END PROCESS nextstate_proc;
 
   -----------------------------------------------------------------
   output_proc : PROCESS ( 
      current_state,
      w_laag,
      wassen_status
   )
   -----------------------------------------------------------------
   BEGIN

      -- Combined Actions
      CASE current_state IS
         WHEN idle => 
            deur_grendel <= w_laag;
            led_start <= '0' ;
            led_status <= "000"; 
            go_wassen <= '0' ;
         WHEN proces => 
            deur_grendel <= '1' ;
            led_start <= '1' ;
            led_status <= "000"; 
            go_wassen <= '0' ;
         WHEN wait_s => 
            deur_grendel <= '1' ;
            led_start <= '1' ;
            led_status <= "000"; 
            go_wassen <= '1' ;
         WHEN started => 
            deur_grendel <= '1' ;
            led_start <= '1' ;
            led_status <= "000"; 
            go_wassen <= '0' ;
         WHEN L_status => 
            led_status <= wassen_status;
            deur_grendel <= '1' ;
            led_start <= '1' ;
            go_wassen <= '0' ;
         WHEN prg_done => 
            led_status <= "000";
            deur_grendel <= '1' ;
            led_start <= '0' ;
            go_wassen <= '0' ;
         WHEN s_spoelstop => 
            led_status <= "101";
            deur_grendel <= '1' ;
            led_start <= '1' ;
            go_wassen <= '0' ;
         WHEN s0 => 
            led_status <= wassen_status;
            deur_grendel <= '1' ;
            led_start <= '1' ;
            go_wassen <= '0' ;
         WHEN s1 => 
            led_status <= "101";
            deur_grendel <= '1' ;
            led_start <= '1' ;
            go_wassen <= '1' ;
         WHEN OTHERS =>
            NULL;
      END CASE;
   END PROCESS output_proc;
 
END Master;
