-- VHDL Entity Wasmachine.wasmachien_block_tb.symbol
--
-- Created:
--          by - Perij.UNKNOWN (LAPTOP-Q0P13GKH)
--          at - 00:18:15 26/02/2025
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.1 Built on 21 Jan 2022 at 13:00:30
--


ENTITY wasmachien_block_tb IS
-- Declarations

END wasmachien_block_tb ;

--
-- VHDL Architecture Wasmachine.wasmachien_block_tb.struct
--
-- Created:
--          by - Perij.UNKNOWN (LAPTOP-Q0P13GKH)
--          at - 15:45:41 11/03/2025
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.1 Built on 21 Jan 2022 at 13:00:30
--
LIBRARY ieee;
USE ieee.std_logic_1164.ALL;
USE ieee.std_logic_arith.ALL;

LIBRARY Wasmachine;

ARCHITECTURE struct OF wasmachien_block_tb IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL aan_uit           : std_logic                    := '0';
   SIGNAL centrifugeerkeuze : std_logic_vector(1 DOWNTO 0) := "01";
   SIGNAL clk               : std_logic                    := '0';
   SIGNAL deur_dicht        : std_logic                    := '1';
   SIGNAL deur_grendel      : std_logic;
   SIGNAL klep_open         : std_logic;
   SIGNAL kuip_leeg         : std_logic                    := '1';
   SIGNAL led_aan           : std_logic;
   SIGNAL led_start         : std_logic;
   SIGNAL led_status        : std_logic_vector(2 DOWNTO 0);
   SIGNAL led_vuldeur       : std_logic;
   SIGNAL motor             : std_logic_vector(2 DOWNTO 0);
   SIGNAL pomp_aan          : std_logic;
   SIGNAL programmakeuze    : std_logic_vector(1 DOWNTO 0) := "00";
   SIGNAL start             : std_logic                    := '0';
   SIGNAL t_hoog            : std_logic                    := '0';
   SIGNAL t_laag            : std_logic                    := '1';
   SIGNAL verwarmen         : std_logic;
   SIGNAL w_hoog            : std_logic                    := '0';
   SIGNAL w_laag            : std_logic                    := '1';


   -- Component Declarations
   COMPONENT wasmachien_block
   PORT (
      aan_uit           : IN     std_logic                     := '0';
      centrifugeerkeuze : IN     std_logic_vector (1 DOWNTO 0) := "01";
      clk               : IN     std_logic                     := '0';
      deur_dicht        : IN     std_logic                     := '1';
      kuip_leeg         : IN     std_logic ;
      programmakeuze    : IN     std_logic_vector (1 DOWNTO 0) := "00";
      start             : IN     std_logic                     := '0';
      t_hoog            : IN     std_logic                     := '0';
      t_laag            : IN     std_logic                     := '0';
      w_hoog            : IN     std_logic                     := '0';
      w_laag            : IN     std_logic                     := '0';
      deur_grendel      : OUT    std_logic                     := '0';
      klep_open         : OUT    std_logic                     := '0';
      led_start         : OUT    std_logic                     := '0';
      led_status        : OUT    std_logic_vector (2 DOWNTO 0) := "000";
      motor             : OUT    std_logic_vector (2 DOWNTO 0) := "000";
      pomp_aan          : OUT    std_logic                     := '0';
      verwarmen         : OUT    std_logic                     := '0'
   );
   END COMPONENT;
   COMPONENT wasmachien_block_tester
   PORT (
      deur_grendel      : IN     std_logic ;
      klep_open         : IN     std_logic ;
      led_aan           : IN     std_logic ;
      led_start         : IN     std_logic ;
      led_status        : IN     std_logic_vector (2 DOWNTO 0);
      led_vuldeur       : IN     std_logic ;
      motor             : IN     std_logic_vector (2 DOWNTO 0);
      pomp_aan          : IN     std_logic ;
      verwarmen         : IN     std_logic ;
      aan_uit           : OUT    std_logic ;
      centrifugeerkeuze : OUT    std_logic_vector (1 DOWNTO 0);
      clk               : OUT    std_logic ;
      deur_dicht        : OUT    std_logic ;
      kuip_leeg         : OUT    std_logic ;
      programmakeuze    : OUT    std_logic_vector (1 DOWNTO 0);
      start             : OUT    std_logic ;
      t_hoog            : OUT    std_logic ;
      t_laag            : OUT    std_logic ;
      w_hoog            : OUT    std_logic ;
      w_laag            : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : wasmachien_block USE ENTITY Wasmachine.wasmachien_block;
   FOR ALL : wasmachien_block_tester USE ENTITY Wasmachine.wasmachien_block_tester;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_0 : wasmachien_block
      PORT MAP (
         aan_uit           => aan_uit,
         centrifugeerkeuze => centrifugeerkeuze,
         clk               => clk,
         deur_dicht        => deur_dicht,
         kuip_leeg         => kuip_leeg,
         programmakeuze    => programmakeuze,
         start             => start,
         t_hoog            => t_hoog,
         t_laag            => t_laag,
         w_hoog            => w_hoog,
         w_laag            => w_laag,
         deur_grendel      => deur_grendel,
         klep_open         => klep_open,
         led_start         => led_start,
         led_status        => led_status,
         motor             => motor,
         pomp_aan          => pomp_aan,
         verwarmen         => verwarmen
      );
   U_1 : wasmachien_block_tester
      PORT MAP (
         deur_grendel      => deur_grendel,
         klep_open         => klep_open,
         led_aan           => led_aan,
         led_start         => led_start,
         led_status        => led_status,
         led_vuldeur       => led_vuldeur,
         motor             => motor,
         pomp_aan          => pomp_aan,
         verwarmen         => verwarmen,
         aan_uit           => aan_uit,
         centrifugeerkeuze => centrifugeerkeuze,
         clk               => clk,
         deur_dicht        => deur_dicht,
         kuip_leeg         => kuip_leeg,
         programmakeuze    => programmakeuze,
         start             => start,
         t_hoog            => t_hoog,
         t_laag            => t_laag,
         w_hoog            => w_hoog,
         w_laag            => w_laag
      );

END struct;
