-- VHDL Entity Wasmachine.Wassen.interface
--
-- Created:
--          by - EIGENAAR.UNKNOWN (DESKTOP-19Q08NH)
--          at - 13:39:22  3-03-2025
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.1 Built on 21 Jan 2022 at 13:00:30
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY Wassen IS
   PORT( 
      aan_uit           : IN     std_logic;
      afpompen_ready    : IN     std_logic;
      centrifugeerkeuze : IN     std_logic_vector (1 DOWNTO 0);
      clk               : IN     std_logic;
      go_wassen         : IN     std_logic;
      programmakeuze    : IN     std_logic_vector (1 DOWNTO 0);
      t_hoog            : IN     std_logic;
      t_laag            : IN     std_logic;
      toevoer_ready     : IN     std_logic;
      trommel_ready     : IN     std_logic;
      verwarmen_ready   : IN     std_logic;
      w_hoog            : IN     std_logic;
      w_laag            : IN     std_logic;
      go_afpompen       : OUT    std_logic;
      go_toevoer        : OUT    std_logic;
      go_trommel        : OUT    std_logic;
      go_verwarmen      : OUT    std_logic;
      wassen_ready      : OUT    std_logic;
      wassen_status     : OUT    std_logic_vector (2 DOWNTO 0)
   );

-- Declarations

END Wassen ;

--
-- VHDL Architecture Wasmachine.Wassen.Wassen
--
-- Created:
--          by - Perij.UNKNOWN (LAPTOP-Q0P13GKH)
--          at - 14:15:30 05/03/2025
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.1 Built on 21 Jan 2022 at 13:00:30
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
 
ARCHITECTURE Wassen OF Wassen IS

   TYPE STATE_TYPE IS (
      s0,
      s1,
      s3,
      s7,
      s9,
      s6,
      s2,
      s4,
      s10,
      s11,
      s13,
      s14,
      s15,
      s16,
      s17,
      s18,
      s8,
      s5,
      s12
   );
 
   -- Declare current and next state signals
   SIGNAL current_state : STATE_TYPE;
   SIGNAL next_state : STATE_TYPE;

BEGIN

   -----------------------------------------------------------------
   clocked_proc : PROCESS ( 
      clk,
      aan_uit
   )
   -----------------------------------------------------------------
   BEGIN
      IF (aan_uit = '0') THEN
         current_state <= s0;
      ELSIF (clk'EVENT AND clk = '1') THEN
         current_state <= next_state;
      END IF;
   END PROCESS clocked_proc;
 
   -----------------------------------------------------------------
   nextstate_proc : PROCESS ( 
      afpompen_ready,
      centrifugeerkeuze,
      current_state,
      go_wassen,
      programmakeuze,
      t_hoog,
      t_laag,
      toevoer_ready,
      trommel_ready,
      verwarmen_ready,
      w_hoog,
      w_laag
   )
   -----------------------------------------------------------------
   BEGIN
      CASE current_state IS
         WHEN s0 => 
            IF (go_wassen = '0') THEN 
               next_state <= s0;
            ELSIF (go_wassen = '1') THEN 
               next_state <= s2;
            ELSE
               next_state <= s0;
            END IF;
         WHEN s1 => 
            IF (programmakeuze = "10" OR programmakeuze = "01") THEN 
               next_state <= s3;
            ELSIF (programmakeuze = "11") THEN 
               next_state <= s1;
            ELSIF (programmakeuze = "00") THEN 
               next_state <= s7;
            ELSE
               next_state <= s1;
            END IF;
         WHEN s3 => 
            IF (go_wassen = '0') THEN 
               next_state <= s3;
            ELSIF (go_wassen = '1') THEN 
               next_state <= s13;
            ELSE
               next_state <= s3;
            END IF;
         WHEN s7 => 
            IF (afpompen_ready = '0') THEN 
               next_state <= s16;
            ELSE
               next_state <= s7;
            END IF;
         WHEN s9 => 
            IF (w_hoog = '1') THEN 
               next_state <= s9;
            ELSIF (toevoer_ready = '0') THEN 
               next_state <= s6;
            ELSE
               next_state <= s9;
            END IF;
         WHEN s6 => 
            IF (trommel_ready = '0') THEN 
               next_state <= s10;
            ELSE
               next_state <= s6;
            END IF;
         WHEN s2 => 
            IF (w_hoog = '0') THEN 
               next_state <= s2;
            ELSIF (toevoer_ready = '0') THEN 
               next_state <= s14;
            ELSE
               next_state <= s2;
            END IF;
         WHEN s4 => 
            IF (centrifugeerkeuze = "11") THEN 
               next_state <= s11;
            ELSIF (centrifugeerkeuze = "01") THEN 
               next_state <= s0;
            ELSE
               next_state <= s4;
            END IF;
         WHEN s10 => 
            IF (t_laag = '1') THEN 
               next_state <= s10;
            ELSIF (afpompen_ready = '0') THEN 
               next_state <= s17;
            ELSE
               next_state <= s10;
            END IF;
         WHEN s11 => 
            IF (trommel_ready = '0') THEN 
               next_state <= s18;
            ELSE
               next_state <= s11;
            END IF;
         WHEN s13 => 
            IF (w_laag = '1') THEN 
               next_state <= s13;
            ELSIF (afpompen_ready = '0') THEN 
               next_state <= s4;
            ELSE
               next_state <= s13;
            END IF;
         WHEN s14 => 
            IF (w_hoog = '1') THEN 
               next_state <= s15;
            ELSE
               next_state <= s14;
            END IF;
         WHEN s15 => 
            IF (trommel_ready = '0') THEN 
               next_state <= s15;
            ELSIF (trommel_ready = '1') THEN 
               next_state <= s5;
            ELSIF (t_laag = '1') THEN 
               next_state <= s8;
            ELSE
               next_state <= s15;
            END IF;
         WHEN s16 => 
            IF (w_laag = '1') THEN 
               next_state <= s9;
            ELSE
               next_state <= s16;
            END IF;
         WHEN s17 => 
            IF (t_laag = '0') THEN 
               next_state <= s0;
            ELSE
               next_state <= s17;
            END IF;
         WHEN s18 => 
            next_state <= s0;
         WHEN s8 => 
            IF (verwarmen_ready = '0') THEN 
               next_state <= s12;
            ELSIF (trommel_ready = '1') THEN 
               next_state <= s5;
            ELSE
               next_state <= s8;
            END IF;
         WHEN s5 => 
            next_state <= s1;
         WHEN s12 => 
            IF (t_hoog = '1' OR trommel_ready = '1') THEN 
               next_state <= s15;
            ELSE
               next_state <= s12;
            END IF;
         WHEN OTHERS =>
            next_state <= s0;
      END CASE;
   END PROCESS nextstate_proc;
 
   -----------------------------------------------------------------
   output_proc : PROCESS ( 
      current_state
   )
   -----------------------------------------------------------------
   BEGIN

      -- Combined Actions
      CASE current_state IS
         WHEN s0 => 
            wassen_ready <= '1';
            wassen_status <= "000";
         WHEN s3 => 
            wassen_status <= "101";
         WHEN s7 => 
            go_afpompen <= '1';
            wassen_status <= "010";
         WHEN s9 => 
            go_toevoer <= '1';
         WHEN s6 => 
            go_trommel <= '1';
            go_toevoer <= '0';
         WHEN s2 => 
            go_toevoer <= '1';
            wassen_ready <= '0';
         WHEN s4 => 
            go_afpompen <= '0';
         WHEN s10 => 
            go_afpompen <= '1';
            go_trommel <= '0';
         WHEN s11 => 
            go_trommel <= '1';
         WHEN s13 => 
            go_afpompen <= '1';
         WHEN s14 => 
            go_toevoer <= '0' ;
         WHEN s15 => 
            go_trommel <= '1';
         WHEN s16 => 
            go_afpompen <= '0';
         WHEN s17 => 
            go_afpompen <= '0';
         WHEN s18 => 
            go_trommel <= '0';
         WHEN s8 => 
            go_verwarmen <= '1';
         WHEN s5 => 
            go_verwarmen <= '0';
            go_trommel <= '0';
         WHEN s12 => 
            go_verwarmen <= '0';
         WHEN OTHERS =>
            NULL;
      END CASE;
   END PROCESS output_proc;
 
END Wassen;
