-- VHDL Entity Wasmachine.Wassen.interface
--
-- Created:
--          by - Perij.UNKNOWN (LAPTOP-Q0P13GKH)
--          at - 14:25:06 26/02/2025
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.1 Built on 21 Jan 2022 at 13:00:30
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY Wassen IS
   PORT( 
      aan_uit             : IN     std_logic;
      afpompen_ready      : IN     std_logic;
      centrifugeerkeuze   : IN     std_logic_vector (1 DOWNTO 0);
      centrifugeren_ready : IN     std_logic;
      clk                 : IN     std_logic;
      go_wassen           : IN     std_logic;
      programmakeuze      : IN     std_logic_vector (1 DOWNTO 0);
      t_hoog              : IN     std_logic;
      t_laag              : IN     std_logic;
      toevoer_ready       : IN     std_logic;
      trommel_ready       : IN     std_logic;
      verwarmen_ready     : IN     std_logic;
      w_hoog              : IN     std_logic;
      w_laag              : IN     std_logic;
      go_afmpompen        : OUT    std_logic;
      go_centrifugeren    : OUT    std_logic;
      go_toevoer          : OUT    std_logic;
      go_trommel          : OUT    std_logic;
      go_verwarmen        : OUT    std_logic;
      wassen_ready        : OUT    std_logic;
      wassen_status       : OUT    std_logic_vector (2 DOWNTO 0)
   );

-- Declarations

END Wassen ;

--
-- VHDL Architecture Wasmachine.Wassen.Wassen
--
-- Created:
--          by - Perij.UNKNOWN (LAPTOP-Q0P13GKH)
--          at - 14:25:06 26/02/2025
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.1 Built on 21 Jan 2022 at 13:00:30
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
 
ARCHITECTURE Wassen OF Wassen IS

   TYPE STATE_TYPE IS (
      s0
   );
 
   -- Declare current and next state signals
   SIGNAL current_state : STATE_TYPE;
   SIGNAL next_state : STATE_TYPE;

BEGIN

   -----------------------------------------------------------------
   clocked_proc : PROCESS ( 
      clk,
      aan_uit
   )
   -----------------------------------------------------------------
   BEGIN
      IF (aan_uit = '1') THEN
         current_state <= s0;
      ELSIF (clk'EVENT AND clk = '1') THEN
         current_state <= next_state;
      END IF;
   END PROCESS clocked_proc;
 
   -----------------------------------------------------------------
   nextstate_proc : PROCESS ( 
      current_state
   )
   -----------------------------------------------------------------
   BEGIN
      CASE current_state IS
         WHEN s0 => 
            next_state <= s0;
         WHEN OTHERS =>
            next_state <= s0;
      END CASE;
   END PROCESS nextstate_proc;
 
END Wassen;
